### PR TITLE
Require interned structs' fields to be `Update`

### LINKED ISSUE #985: Unsoundness: Interned values can store references
For example, the following test triggers Miri, because we attempt to access the previous value when re-interning.

```rust
#[salsa::input]
struct Input {
    #[returns(ref)]
    field1: Box<usize>,
}

#[salsa::interned]
struct Interned<'db> {
    field1: &'db Box<usize>,
}

#[test]
fn test() {
    #[salsa::tracked]
    fn intern<'db>(db: &'db dyn Database, input: Input) -> Interned<'db> {
        Interned::new(db, input.field1(db))
    }

    let mut db = common::LoggerDatabase::default();

    let input = Input::new(&db, Box::new(100));

    let _interned = intern(&db, input);

    input.set_field1(&mut db).to(Box::new(100));

    let interned = intern(&db, input);
    dbg!(interned.field1(&db));
}
```
```rust
 error: Undefined Behavior: trying to retag from <471448> for SharedReadOnly permission at alloc187151[0x0], but that tag does not exist in the borrow stack for this location
    --> /home/ibraheem/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:2029:27
     |
2029 |             PartialEq::eq(*self, *other)
     |                           ^^^^^ this error occurs as part of retag at alloc187151[0x0..0x8]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
```

We probably need to enforce `salsa::Update` for the fields of interned values, similar to tracked structs. https://github.com/salsa-rs/salsa/issues/681 is relevant.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
To fix an unsoundness - #985.

There are two breaking changes here:

 1. Interned fields and interned function fields are required to be `Update` (or `'static`)
 2. `unsafe(non_update_return_types)` in tracked fn options was renamed to `unsafe(non_update_types)` (and includes interned parameters as well now).

Fixes #985.

### CODE REVIEW

File: components/salsa-macros/src/tracked_fn.rs [hunk 1]
```diff
@@ -191,17 +191,12 @@ impl Macro {
         // want, so by uniformly using `output_ty.span()` we ensure that the diagnostic is emitted
         // at the return type in the original input.
         // See the tests/compile-fail/tracked_fn_return_ref.rs test
```
Comment (Veykril) [inline components/salsa-macros/src/tracked_fn.rs]: The comment should move to that new function i think?

**Comment by MichaReiser** [comment]
Does this fix https://github.com/salsa-rs/salsa/issues/985

Can we add two non-compile tests:

1. For an interned struct storing a reference
2. For a multi-argument tracked query, taking a reference as the argument

**Comment by ChayimFriedman2** [comment]
> Does this fix #985

Yes.

> Can we add two non-compile tests:
> 
>     1. For an interned struct storing a reference
> 
>     2. For a multi-argument tracked query, taking a reference as the argument

I added them as one, except storing a lifetime'd struct instead of a reference.

File: tests/compile-fail/interned_not_update.rs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+use salsa::Database as Db;
+
+#[salsa::input]
+struct MyInput {}
+
+#[derive(Clone, Debug, PartialEq, Eq, Hash)]
+struct NotUpdate<'db>(&'db ());
+
+#[salsa::tracked]
+fn tracked_fn<'db>(_db: &'db dyn Db, _: (), _: NotUpdate<'db>) {}
```
Comment (MichaReiser) [inline tests/compile-fail/interned_not_update.rs]: Nit, I would probalby just use a `&str` here, it should be sufficient for demonstration purposes

```suggestion
fn tracked_fn<'db>(_db: &'db dyn Db, _: (), _not_update: &'db str) {}
```

**Review by MichaReiser — APPROVED** [review]
Thank you

**Comment by ChayimFriedman2** [comment]
Can we get a release with this please? It's needed for rust-analyzer.
